import { existsSync, readFileSync } from 'node:fs';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { EMBEDDED_FLEET_JSON } from './canonical-fleet.embedded.ts';

/**
 * S5 — canonical cron fleet loader.
 *
 * The single source of truth for the platform's cron jobs is
 * scripts/cron-fleet.json (20 canonical jobs + the hourly system
 * watchdog). This module reads it with fs — deliberately NOT a JSON
 * import, so the file stays a plain ops artifact that scripts/ and the
 * sync-crons route can share without bundler tricks.
 *
 * Runtime safety: if the JSON file is not present on disk (minimal
 * serverless bundle), it falls back to the autogenerated embedded
 * snapshot in canonical-fleet.embedded.ts. A unit test fails loudly if
 * the snapshot ever drifts from the file, and the loader reports which
 * source it used.
 */

export interface CronScheduleSpec {
  mdays: number[];
  months: number[];
  wdays: number[];
  hours: number[];
  minutes: number[];
  timezone: string;
  expiresAt: number;
}

export interface CronJobSpec {
  /** Stable identity of the job (used for dupe/stale detection). */
  key: string;
  title: string;
  /** May contain {baseUrl}/{operatorUrl} placeholders. */
  url: string;
  schedule: CronScheduleSpec;
  /** 'cron-secret' -> Authorization: Bearer <CRON_SECRET>; null -> no auth header. */
  auth: 'cron-secret' | null;
}

export interface CronFleet {
  version: number;
  baseUrl: string;
  operatorUrl: string;
  timezone: string;
  jobs: CronJobSpec[];
  watchdog: CronJobSpec;
}

export interface LoadedFleet {
  fleet: CronFleet;
  /** 'fs' when scripts/cron-fleet.json was read from disk, else 'embedded'. */
  source: 'fs' | 'embedded';
  /** Absolute path of the file that was read (fs source only). */
  path?: string;
}

/** Candidate locations of scripts/cron-fleet.json, in priority order. */
export function fleetJsonCandidates(cwd: string = process.cwd()): string[] {
  const here = dirname(fileURLToPath(import.meta.url)); // .../apps/main/lib/cron
  const repoRootFromHere = resolve(here, '..', '..', '..', '..');
  const candidates = [
    process.env.FLEET_JSON_PATH ? resolve(process.env.FLEET_JSON_PATH) : null,
    join(cwd, 'scripts/cron-fleet.json'),
    join(cwd, '..', '..', 'scripts/cron-fleet.json'), // cwd = apps/main
    join(repoRootFromHere, 'scripts/cron-fleet.json'),
    '/var/task/scripts/cron-fleet.json', // Vercel function root
  ].filter((c): c is string => Boolean(c));
  // De-dupe while preserving order.
  return Array.from(new Set(candidates.map((c) => resolve(c))));
}

export function readFleetJsonText(cwd?: string): { text: string; path: string } | null {
  // Test hook: force the embedded-snapshot path even when the repo file
  // exists on disk (proves the serverless fallback parses identically).
  if (process.env.FLEET_JSON_DISABLE_FS === '1') return null;
  for (const candidate of fleetJsonCandidates(cwd)) {
    try {
      if (existsSync(candidate)) {
        return { text: readFileSync(candidate, 'utf8'), path: candidate };
      }
    } catch {
      // unreadable candidate — try the next one
    }
  }
  return null;
}

/** Substitute {baseUrl}/{operatorUrl} placeholders using fleet defaults + env overrides. */
export function resolveJobUrl(
  url: string,
  fleet: Pick<CronFleet, 'baseUrl' | 'operatorUrl'>,
  env: Record<string, string | undefined> = process.env
): string {
  const baseUrl = (env.NEXT_PUBLIC_APP_URL || env.APP_URL || fleet.baseUrl).replace(/\/$/, '');
  const operatorUrl = (env.OPERATOR_URL || fleet.operatorUrl).replace(/\/$/, '');
  return url.replace(/\{baseUrl\}/g, baseUrl).replace(/\{operatorUrl\}/g, operatorUrl);
}

/** Parse + validate raw fleet JSON text. Throws on any structural problem. */
export function parseFleet(text: string): CronFleet {
  const raw = JSON.parse(text) as CronFleet;
  if (!raw || typeof raw !== 'object') throw new Error('cron-fleet.json: not an object');
  if (!Array.isArray(raw.jobs)) throw new Error('cron-fleet.json: jobs[] missing');
  if (!raw.watchdog || typeof raw.watchdog !== 'object') {
    throw new Error('cron-fleet.json: watchdog job missing');
  }
  const seen = new Set<string>();
  for (const job of [...raw.jobs, raw.watchdog]) {
    if (!job.key || !job.title || !job.url || !job.schedule) {
      throw new Error(`cron-fleet.json: job missing key/title/url/schedule: ${JSON.stringify(job)}`);
    }
    if (seen.has(job.key)) throw new Error(`cron-fleet.json: duplicate job key ${job.key}`);
    seen.add(job.key);
    for (const field of ['mdays', 'months', 'wdays', 'hours', 'minutes'] as const) {
      if (!Array.isArray(job.schedule[field])) {
        throw new Error(`cron-fleet.json: job ${job.key} schedule.${field} must be an array`);
      }
    }
  }
  return raw;
}

/**
 * Load the canonical fleet. Prefers scripts/cron-fleet.json on disk (fs);
 * falls back to the embedded snapshot when no file is found.
 */
export function loadCanonicalFleet(cwd?: string): LoadedFleet {
  const fromDisk = readFleetJsonText(cwd);
  if (fromDisk) {
    return { fleet: parseFleet(fromDisk.text), source: 'fs', path: fromDisk.path };
  }
  return { fleet: parseFleet(EMBEDDED_FLEET_JSON), source: 'embedded' };
}

export interface ResolvedCronJob {
  key: string;
  title: string;
  url: string;
  schedule: CronScheduleSpec;
  auth: 'cron-secret' | null;
  isWatchdog: boolean;
}

/**
 * The full fleet — 20 canonical jobs + watchdog — with URLs resolved
 * against the configured base/operator URLs.
 */
export function resolveFleetJobs(
  loaded: LoadedFleet,
  env: Record<string, string | undefined> = process.env
): ResolvedCronJob[] {
  const { fleet } = loaded;
  const map = (job: CronJobSpec, isWatchdog: boolean): ResolvedCronJob => ({
    key: job.key,
    title: job.title,
    url: resolveJobUrl(job.url, fleet, env),
    schedule: job.schedule,
    auth: job.auth ?? null,
    isWatchdog,
  });
  return [...fleet.jobs.map((j) => map(j, false)), map(fleet.watchdog, true)];
}
