// GENERATED by scripts/gen-gate-ddl.mjs — do not edit by hand.
// Inline copy of ddl.sql for the pg-mem gate mock (see file header there).
export const GATE_DDL =
  `CREATE TABLE IF NOT EXISTS "campaigns" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"audience_filter" jsonb DEFAULT '{}'::jsonb,
	"message" text NOT NULL,
	"sent_count" integer DEFAULT 0,
	"sent_at" timestamp,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "contacts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"phone" text NOT NULL,
	"name" text,
	"blocklisted" boolean DEFAULT false NOT NULL,
	"vip" boolean DEFAULT false NOT NULL,
	"loyalty_points" integer DEFAULT 0 NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "conversations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"contact_id" uuid NOT NULL,
	"wa_account_id" uuid,
	"manual_takeover" boolean DEFAULT false NOT NULL,
	"is_resolved" boolean DEFAULT false NOT NULL,
	"last_message_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "jobs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"max_attempts" integer DEFAULT 5 NOT NULL,
	"next_run_at" timestamp DEFAULT now() NOT NULL,
	"last_error" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "leads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"contact_id" uuid,
	"type" text NOT NULL,
	"status" text DEFAULT 'new' NOT NULL,
	"data" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "loyalty_rewards" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"name" text NOT NULL,
	"points_cost" integer NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "loyalty_transactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"contact_id" uuid NOT NULL,
	"type" text NOT NULL,
	"amount" integer NOT NULL,
	"description" text,
	"created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"conversation_id" uuid NOT NULL,
	"direction" text NOT NULL,
	"content" text NOT NULL,
	"is_ai_generated" boolean DEFAULT false NOT NULL,
	"sentiment" text,
	"message_type" text DEFAULT 'text',
	"wa_message_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "reservations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"contact_id" uuid,
	"customer_name" text,
	"customer_phone" text,
	"date" timestamp NOT NULL,
	"party_size" integer NOT NULL,
	"status" text DEFAULT 'confirmed' NOT NULL,
	"deposit" numeric(10, 2),
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "staff_members" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid,
	"clerk_user_id" text NOT NULL,
	"email" text,
	"name" text,
	"role" text DEFAULT 'staff' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "system_settings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"master_ai_switch" boolean DEFAULT true NOT NULL,
	"maintenance_mode" boolean DEFAULT false NOT NULL,
	"global_notice" text,
	"updated_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "tenants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"owner_email" text,
	"description" text,
	"opening_hours" text,
	"ai_personality" text DEFAULT 'friendly and professional',
	"ai_enabled" boolean DEFAULT true NOT NULL,
	"manual_mode" boolean DEFAULT false NOT NULL,
	"system_prompt" text,
	"monthly_fee" numeric(10, 2) DEFAULT '49.00',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "tenants_slug_unique" UNIQUE("slug")
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "wa_account_bindings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"wa_account_id" uuid NOT NULL,
	"app_id" text NOT NULL,
	"tenant_id" uuid NOT NULL,
	"webhook_url" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "wa_accounts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"phone_number" text,
	"session_creds" text,
	"is_connected" boolean DEFAULT false NOT NULL,
	"qr_code" text,
	"status" text DEFAULT 'unlinked',
	"last_connected_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "wa_auth_keys" (
	"wa_account_id" uuid NOT NULL,
	"key_type" text NOT NULL,
	"key_id" text NOT NULL,
	"value" jsonb
)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "waitlist_entries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"contact_id" uuid NOT NULL,
	"customer_name" text,
	"customer_phone" text,
	"party_size" integer NOT NULL,
	"status" text DEFAULT 'waiting' NOT NULL,
	"estimated_wait_minutes" integer DEFAULT 20,
	"notified_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
ALTER TABLE "campaigns" ADD CONSTRAINT "campaigns_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "contacts" ADD CONSTRAINT "contacts_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_contact_id_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."contacts"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_wa_account_id_wa_accounts_id_fk" FOREIGN KEY ("wa_account_id") REFERENCES "public"."wa_accounts"("id") ON DELETE set null ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "leads" ADD CONSTRAINT "leads_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "leads" ADD CONSTRAINT "leads_contact_id_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."contacts"("id") ON DELETE set null ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "loyalty_rewards" ADD CONSTRAINT "loyalty_rewards_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_contact_id_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."contacts"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "messages" ADD CONSTRAINT "messages_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_contact_id_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."contacts"("id") ON DELETE set null ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "staff_members" ADD CONSTRAINT "staff_members_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "wa_accounts" ADD CONSTRAINT "wa_accounts_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "wa_auth_keys" ADD CONSTRAINT "wa_auth_keys_wa_account_id_wa_accounts_id_fk" FOREIGN KEY ("wa_account_id") REFERENCES "public"."wa_accounts"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "waitlist_entries" ADD CONSTRAINT "waitlist_entries_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "waitlist_entries" ADD CONSTRAINT "waitlist_entries_contact_id_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."contacts"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS "contacts_tenant_phone_idx" ON "contacts" USING btree ("tenant_id","phone")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "contacts_phone_idx" ON "contacts" USING btree ("phone")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "jobs_status_next_run_idx" ON "jobs" USING btree ("status","next_run_at")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "messages_tenant_created_idx" ON "messages" USING btree ("tenant_id","created_at")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "messages_conversation_idx" ON "messages" USING btree ("conversation_id")
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS "messages_wa_message_id_unique" ON "messages" USING btree ("tenant_id","wa_message_id") WHERE "messages"."wa_message_id" IS NOT NULL
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS "wa_auth_keys_pk" ON "wa_auth_keys" USING btree ("wa_account_id","key_type","key_id")
-- @@GATE-STATEMENT@@
ALTER TABLE "conversations" ADD COLUMN IF NOT EXISTS "outcome" text
-- @@GATE-STATEMENT@@
ALTER TABLE "conversations" ADD COLUMN IF NOT EXISTS "estimated_value_cents" integer DEFAULT 0 NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE "conversations" ADD COLUMN IF NOT EXISTS "outcome_classified_at" timestamp
-- @@GATE-STATEMENT@@
ALTER TABLE "conversations" ADD COLUMN IF NOT EXISTS "outcome_classifier" text
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD COLUMN IF NOT EXISTS "conversation_id" uuid
-- @@GATE-STATEMENT@@
ALTER TABLE "waitlist_entries" ADD COLUMN IF NOT EXISTS "conversation_id" uuid
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "revenue_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"event_type" text NOT NULL,
	"conversation_id" uuid,
	"estimated_value_cents" integer DEFAULT 0 NOT NULL,
	"realized_cents" integer DEFAULT 0 NOT NULL,
	"occurred_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE set null ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "waitlist_entries" ADD CONSTRAINT "waitlist_entries_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE set null ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "revenue_events" ADD CONSTRAINT "revenue_events_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
-- @@GATE-STATEMENT@@
ALTER TABLE "revenue_events" ADD CONSTRAINT "revenue_events_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE set null ON UPDATE no action;
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "conversations_outcome_tenant_idx" ON "conversations" USING btree ("tenant_id","outcome","outcome_classified_at")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "revenue_events_tenant_occurred_idx" ON "revenue_events" USING btree ("tenant_id","occurred_at")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "revenue_events_conversation_idx" ON "revenue_events" USING btree ("conversation_id")
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD COLUMN IF NOT EXISTS "cancelled_at" timestamp
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD COLUMN IF NOT EXISTS "cancellation_followup_sent" boolean DEFAULT false NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD COLUMN IF NOT EXISTS "cancellation_followup_sent_at" timestamp
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "reservations_cancellation_followup_idx"
  ON "reservations" ("cancelled_at")
  WHERE "status" = 'cancelled' AND "cancellation_followup_sent" = false
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD COLUMN IF NOT EXISTS "no_show_detected" boolean DEFAULT false NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD COLUMN IF NOT EXISTS "no_show_detected_at" timestamp
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD COLUMN IF NOT EXISTS "no_show_followup_sent" boolean DEFAULT false NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD COLUMN IF NOT EXISTS "no_show_followup_sent_at" timestamp
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "reservations_no_show_detection_idx"
  ON "reservations" ("date")
  WHERE "status" = 'confirmed' AND "no_show_detected" = false
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "reservations_no_show_followup_idx"
  ON "reservations" ("no_show_detected_at")
  WHERE "no_show_followup_sent" = false AND "no_show_detected_at" IS NOT NULL
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "customer_profiles" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL REFERENCES "tenants"("id") ON DELETE CASCADE,
  "contact_id" uuid REFERENCES "contacts"("id") ON DELETE SET NULL,
  "customer_phone" text NOT NULL,
  "customer_name" text,
  "total_visits" integer DEFAULT 0 NOT NULL,
  "total_spend_cents" integer DEFAULT 0 NOT NULL,
  "avg_party_size" numeric DEFAULT 0 NOT NULL,
  "last_visit_at" timestamp,
  "first_visit_at" timestamp,
  "preferences" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp DEFAULT NOW() NOT NULL,
  "updated_at" timestamp DEFAULT NOW() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "customer_profiles_tenant_idx" ON "customer_profiles" ("tenant_id")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "customer_profiles_phone_idx" ON "customer_profiles" ("customer_phone")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "customer_profiles_contact_idx" ON "customer_profiles" ("contact_id")
-- @@GATE-STATEMENT@@
ALTER TABLE "customer_profiles"
  ADD COLUMN IF NOT EXISTS "segment" text DEFAULT 'new' NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE "customer_profiles"
  ADD COLUMN IF NOT EXISTS "segment_confidence" numeric DEFAULT 0 NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE "customer_profiles"
  ADD COLUMN IF NOT EXISTS "segment_updated_at" timestamp
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "customer_profiles_segment_idx"
  ON "customer_profiles" ("segment")
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "reactivation_campaigns" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
	"customer_phone" text NOT NULL,
	"segment" text NOT NULL,
	"message_text" text NOT NULL,
	"sent_at" timestamp,
	"responded" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "reactivation_campaigns_tenant_idx" ON "reactivation_campaigns" ("tenant_id")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "reactivation_campaigns_phone_idx" ON "reactivation_campaigns" ("customer_phone")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "reactivation_campaigns_pending_idx" ON "reactivation_campaigns" ("tenant_id","sent_at") WHERE "sent_at" IS NULL
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "vip_alerts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
	"customer_phone" text NOT NULL,
	"customer_name" text,
	"total_visits" integer NOT NULL,
	"total_spend_cents" integer NOT NULL,
	"last_visit_at" timestamp NOT NULL,
	"preferences" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"sent_at" timestamp DEFAULT now() NOT NULL,
	"served_at" timestamp,
	"note" text
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "vip_alerts_tenant_idx" ON "vip_alerts" ("tenant_id")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "vip_alerts_phone_idx" ON "vip_alerts" ("customer_phone")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "vip_alerts_sent_idx" ON "vip_alerts" ("sent_at")
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "google_reviews" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  "google_place_id" text NOT NULL,
  "review_id" text NOT NULL UNIQUE,
  "author_name" text NOT NULL,
  "rating" integer NOT NULL,
  "text" text,
  "time" timestamp NOT NULL,
  "sentiment" text DEFAULT 'neutral' NOT NULL,
  "response_text" text,
  "response_sent_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "google_reviews_tenant_idx" ON "google_reviews" ("tenant_id")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "google_reviews_rating_idx" ON "google_reviews" ("rating")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "google_reviews_time_idx" ON "google_reviews" ("time")
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "google_places_config" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  "place_id" text NOT NULL,
  "api_key_encrypted" text,
  "last_fetch_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS "google_places_config_tenant_uniq" ON "google_places_config" ("tenant_id")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "google_places_config_tenant_idx" ON "google_places_config" ("tenant_id")
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD COLUMN IF NOT EXISTS "review_request_sent" boolean DEFAULT false NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE "reservations" ADD COLUMN IF NOT EXISTS "review_request_sent_at" timestamp
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "reservations_review_request_idx"
  ON "reservations" ("review_request_sent", "date")
  WHERE status IN ('confirmed', 'completed') AND review_request_sent = false
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "competitors" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  "name" text NOT NULL,
  "google_place_id" text NOT NULL,
  "current_rating" numeric DEFAULT '0' NOT NULL,
  "review_count" integer DEFAULT 0 NOT NULL,
  "last_check_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "competitors_tenant_idx" ON "competitors" ("tenant_id")
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "competitor_rating_history" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "competitor_id" uuid NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
  "rating" numeric NOT NULL,
  "review_count" integer NOT NULL,
  "recorded_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "competitor_rating_history_competitor_idx" ON "competitor_rating_history" ("competitor_id")
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "competitors" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  "name" text NOT NULL,
  "google_place_id" text,
  "current_rating" numeric DEFAULT '0' NOT NULL,
  "review_count" integer DEFAULT 0 NOT NULL,
  "last_check_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
ALTER TABLE "competitors" ADD COLUMN IF NOT EXISTS "address" text
-- @@GATE-STATEMENT@@
ALTER TABLE "competitors" ADD COLUMN IF NOT EXISTS "latitude" numeric
-- @@GATE-STATEMENT@@
ALTER TABLE "competitors" ADD COLUMN IF NOT EXISTS "longitude" numeric
-- @@GATE-STATEMENT@@
ALTER TABLE "competitors" ADD COLUMN IF NOT EXISTS "distance_km" numeric
-- @@GATE-STATEMENT@@
ALTER TABLE "competitors" ADD COLUMN IF NOT EXISTS "website_url" text
-- @@GATE-STATEMENT@@
ALTER TABLE "competitors" ADD COLUMN IF NOT EXISTS "phone" text
-- @@GATE-STATEMENT@@
ALTER TABLE "competitors" ADD COLUMN IF NOT EXISTS "place_data" jsonb DEFAULT '{}'::jsonb NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE "competitors" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now() NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE "competitors" ALTER COLUMN "google_place_id" DROP NOT NULL
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "competitors_distance_idx" ON "competitors" ("distance_km")
-- @@GATE-STATEMENT@@
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "address" text
-- @@GATE-STATEMENT@@
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "latitude" numeric
-- @@GATE-STATEMENT@@
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "longitude" numeric
-- @@GATE-STATEMENT@@
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "menu_text" text
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "competitor_menu_snapshots" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "competitor_id" uuid NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
  "menu_url" text,
  "menu_text" text,
  "price_range" text,
  "snapshot_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "competitor_menu_snapshots_competitor_idx" ON "competitor_menu_snapshots" ("competitor_id")
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "competitor_promotions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "competitor_id" uuid NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
  "promotion_text" text NOT NULL,
  "source" text,
  "detected_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "competitor_promotions_competitor_idx" ON "competitor_promotions" ("competitor_id")
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "market_opportunities" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  "key" text NOT NULL,
  "opportunity_type" text NOT NULL,
  "title" text NOT NULL,
  "description" text NOT NULL,
  "confidence" numeric DEFAULT '0' NOT NULL,
  "evidence" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "addressed" boolean DEFAULT false NOT NULL,
  "addressed_at" timestamp,
  "detected_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "market_opportunities_tenant_idx" ON "market_opportunities" ("tenant_id")
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS "market_opportunities_tenant_key_uniq" ON "market_opportunities" ("tenant_id", "key")
-- @@GATE-STATEMENT@@
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS channel text DEFAULT 'whatsapp' NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS external_id text
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS conversations_tenant_channel_idx ON conversations (tenant_id, channel)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS conversations_tenant_external_idx ON conversations (tenant_id, external_id)
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS description text
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS target_segment text
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS offer text
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS start_date timestamp
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS end_date timestamp
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS launched_at timestamp
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS estimated_reach integer
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS estimated_revenue_cents integer
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS campaigns_tenant_status_idx ON campaigns (tenant_id, status)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS channel_configs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  channel text NOT NULL,
  credentials_encrypted text,
  enabled boolean DEFAULT false NOT NULL,
  created_at timestamp DEFAULT NOW() NOT NULL,
  updated_at timestamp DEFAULT NOW() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS channel_configs_tenant_channel_idx ON channel_configs (tenant_id, channel)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS channel_configs_tenant_idx ON channel_configs (tenant_id)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS approval_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  message_text text NOT NULL,
  risk_level text NOT NULL,
  status text DEFAULT 'pending' NOT NULL,
  approved_by text,
  approved_at timestamp,
  created_at timestamp DEFAULT NOW() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS approval_requests_tenant_status_idx ON approval_requests (tenant_id, status)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS approval_requests_conversation_idx ON approval_requests (conversation_id)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "marketing_briefs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  "brief" jsonb NOT NULL,
  "generated_at" timestamp DEFAULT now() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "marketing_briefs_tenant_idx" ON "marketing_briefs" ("tenant_id")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "marketing_briefs_tenant_generated_idx" ON "marketing_briefs" ("tenant_id", "generated_at")
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "marketing_campaigns" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
	"name" text NOT NULL,
	"description" text,
	"type" text NOT NULL,
	"target_segment" text,
	"offer" text,
	"message" text NOT NULL,
	"start_date" timestamp,
	"end_date" timestamp,
	"launched_at" timestamp,
	"estimated_reach" integer,
	"estimated_revenue_cents" integer,
	"sent_count" integer DEFAULT 0 NOT NULL,
	"sent_at" timestamp,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" timestamp DEFAULT NOW() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "marketing_campaigns_tenant_idx" ON "marketing_campaigns" ("tenant_id")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "marketing_campaigns_tenant_status_idx" ON "marketing_campaigns" ("tenant_id", "status")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "marketing_campaigns_tenant_type_idx" ON "marketing_campaigns" ("tenant_id", "type")
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS "marketing_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
	"name" text NOT NULL,
	"description" text,
	"event_type" text NOT NULL,
	"starts_at" timestamp NOT NULL,
	"ends_at" timestamp NOT NULL,
	"location" text,
	"capacity" integer,
	"booked_count" integer DEFAULT 0 NOT NULL,
	"message" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" timestamp DEFAULT NOW() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "marketing_events_tenant_idx" ON "marketing_events" ("tenant_id")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "marketing_events_tenant_status_idx" ON "marketing_events" ("tenant_id", "status")
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS "marketing_events_tenant_type_idx" ON "marketing_events" ("tenant_id", "event_type")
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS plan text DEFAULT 'trial' NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS plan_status text DEFAULT 'trialing' NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS trial_ends_at timestamp DEFAULT (now() + interval '14 days') NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS payfast_customer_token text
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS payfast_subscription_token text
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS onboarding_complete boolean DEFAULT false NOT NULL
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS consent_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  consent_version text NOT NULL,
  consented_at timestamp DEFAULT NOW() NOT NULL,
  ip_address text,
  user_agent text,
  created_at timestamp DEFAULT NOW() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS consent_records_tenant_idx ON consent_records (tenant_id)
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS owner_id text
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS tenant_mode text DEFAULT 'live' NOT NULL
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS brand_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  source_url text,
  logo_url text,
  logo_path text,
  primary_color text,
  secondary_color text,
  background_color text,
  font_family text,
  brand_name text,
  tagline text,
  menu_json jsonb,
  hours_json jsonb,
  google_places_id text,
  confidence real,
  extracted_at timestamp
)
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS brand_profiles_tenant_uniq ON brand_profiles (tenant_id)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS prospects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  website text NOT NULL,
  owner_email text,
  owner_phone text,
  city text,
  status text DEFAULT 'queued' NOT NULL,
  error text,
  retries integer DEFAULT 0 NOT NULL,
  tenant_id uuid REFERENCES tenants(id) ON DELETE SET NULL,
  claim_token text,
  claimed_at timestamp,
  created_at timestamp DEFAULT NOW() NOT NULL,
  updated_at timestamp DEFAULT NOW() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS prospects_status_idx ON prospects (status)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS prospects_tenant_idx ON prospects (tenant_id)
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS prospects_claim_token_uniq ON prospects (claim_token)
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS tenant_claim_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  token text NOT NULL,
  created_at timestamp DEFAULT NOW() NOT NULL,
  claimed_at timestamp,
  claimed_by_user_id text,
  expires_at timestamp NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS tenant_claim_tokens_token_uniq ON tenant_claim_tokens (token)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS tenant_claim_tokens_tenant_id_idx ON tenant_claim_tokens (tenant_id)
-- @@GATE-STATEMENT@@
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS birthday text
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS owner_user_id text
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS memberships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  user_id text NOT NULL,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  role text DEFAULT 'owner' NOT NULL,
  created_at timestamp DEFAULT NOW() NOT NULL,
  updated_at timestamp DEFAULT NOW() NOT NULL
)
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS memberships_user_tenant_uniq ON memberships (user_id, tenant_id)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS memberships_user_idx ON memberships (user_id)
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS memberships_tenant_idx ON memberships (tenant_id)
-- @@GATE-STATEMENT@@
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS cronjob_api_key text
-- @@GATE-STATEMENT@@
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS demo_seed_active boolean DEFAULT false NOT NULL
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS description text;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS opening_hours text;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS ai_personality text DEFAULT 'friendly and professional';
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS owner_email text;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS system_prompt text;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT NOW();
-- @@GATE-STATEMENT@@
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS manual_takeover boolean DEFAULT false;
-- @@GATE-STATEMENT@@
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS is_resolved boolean DEFAULT false;
-- @@GATE-STATEMENT@@
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS outcome text;
-- @@GATE-STATEMENT@@
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS estimated_value_cents integer DEFAULT 0;
-- @@GATE-STATEMENT@@
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS outcome_classified_at timestamp;
-- @@GATE-STATEMENT@@
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS outcome_classifier text;
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS conversations_outcome_tenant_idx
        ON conversations (tenant_id, outcome, outcome_classified_at);
-- @@GATE-STATEMENT@@
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS blocklisted boolean DEFAULT false;
-- @@GATE-STATEMENT@@
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS vip boolean DEFAULT false;
-- @@GATE-STATEMENT@@
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS loyalty_points integer DEFAULT 0;
-- @@GATE-STATEMENT@@
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS birthday text;
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS staff_members (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        tenant_id uuid REFERENCES tenants(id) ON DELETE CASCADE,
        clerk_user_id text NOT NULL,
        email text,
        name text,
        role text NOT NULL DEFAULT 'staff',
        created_at timestamp DEFAULT NOW()
      );
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS wa_auth_keys (
        wa_account_id uuid NOT NULL REFERENCES wa_accounts(id) ON DELETE CASCADE,
        key_type text NOT NULL,
        key_id text NOT NULL,
        value jsonb
      );
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS wa_auth_keys_pk
        ON wa_auth_keys (wa_account_id, key_type, key_id);
-- @@GATE-STATEMENT@@
ALTER TABLE messages ADD COLUMN IF NOT EXISTS wa_message_id text;
-- @@GATE-STATEMENT@@
DROP INDEX IF EXISTS messages_wa_message_id_idx;
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS messages_wa_message_id_unique
        ON messages (tenant_id, wa_message_id)
        WHERE wa_message_id IS NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT NOW();
-- @@GATE-STATEMENT@@
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS conversation_id uuid REFERENCES conversations(id) ON DELETE SET NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE waitlist_entries ADD COLUMN IF NOT EXISTS conversation_id uuid REFERENCES conversations(id) ON DELETE SET NULL;
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS revenue_events (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        event_type text NOT NULL,
        conversation_id uuid REFERENCES conversations(id) ON DELETE SET NULL,
        estimated_value_cents integer DEFAULT 0 NOT NULL,
        realized_cents integer DEFAULT 0 NOT NULL,
        occurred_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS revenue_events_tenant_occurred_idx
        ON revenue_events (tenant_id, occurred_at);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS revenue_events_conversation_idx
        ON revenue_events (conversation_id);
-- @@GATE-STATEMENT@@
ALTER TABLE messages ADD COLUMN IF NOT EXISTS delivery_status text;
-- @@GATE-STATEMENT@@
ALTER TABLE messages ADD COLUMN IF NOT EXISTS delivery_error text;
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS messages_delivery_status_idx
        ON messages (tenant_id, delivery_status)
        WHERE delivery_status IS NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS cancelled_at timestamp;
-- @@GATE-STATEMENT@@
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS cancellation_followup_sent boolean DEFAULT false NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS cancellation_followup_sent_at timestamp;
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS reservations_cancellation_followup_idx
        ON reservations (cancelled_at)
        WHERE status = 'cancelled' AND cancellation_followup_sent = false;
-- @@GATE-STATEMENT@@
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS no_show_detected boolean DEFAULT false NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS no_show_detected_at timestamp;
-- @@GATE-STATEMENT@@
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS no_show_followup_sent boolean DEFAULT false NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS no_show_followup_sent_at timestamp;
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS reservations_no_show_detection_idx
        ON reservations (date)
        WHERE status = 'confirmed' AND no_show_detected = false;
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS reservations_no_show_followup_idx
        ON reservations (no_show_detected_at)
        WHERE no_show_followup_sent = false AND no_show_detected_at IS NOT NULL;
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS customer_profiles (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        contact_id uuid REFERENCES contacts(id) ON DELETE SET NULL,
        customer_phone text NOT NULL,
        customer_name text,
        total_visits integer DEFAULT 0 NOT NULL,
        total_spend_cents integer DEFAULT 0 NOT NULL,
        avg_party_size numeric DEFAULT 0 NOT NULL,
        last_visit_at timestamp,
        first_visit_at timestamp,
        preferences jsonb DEFAULT '{}'::jsonb NOT NULL,
        segment text DEFAULT 'new' NOT NULL,
        segment_confidence numeric DEFAULT 0 NOT NULL,
        segment_updated_at timestamp,
        created_at timestamp DEFAULT NOW() NOT NULL,
        updated_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS customer_profiles_tenant_idx ON customer_profiles (tenant_id);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS customer_profiles_phone_idx ON customer_profiles (customer_phone);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS customer_profiles_contact_idx ON customer_profiles (contact_id);
-- @@GATE-STATEMENT@@
ALTER TABLE customer_profiles ADD COLUMN IF NOT EXISTS segment text DEFAULT 'new' NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE customer_profiles ADD COLUMN IF NOT EXISTS segment_confidence numeric DEFAULT 0 NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE customer_profiles ADD COLUMN IF NOT EXISTS segment_updated_at timestamp;
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS customer_profiles_segment_idx ON customer_profiles (segment);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS reactivation_campaigns (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        customer_phone text NOT NULL,
        segment text NOT NULL,
        message_text text NOT NULL,
        sent_at timestamp,
        responded boolean DEFAULT false NOT NULL,
        created_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS reactivation_campaigns_tenant_idx ON reactivation_campaigns (tenant_id);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS reactivation_campaigns_phone_idx ON reactivation_campaigns (customer_phone);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS reactivation_campaigns_pending_idx
        ON reactivation_campaigns (tenant_id, sent_at)
        WHERE sent_at IS NULL;
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS vip_alerts (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        customer_phone text NOT NULL,
        customer_name text,
        total_visits integer NOT NULL,
        total_spend_cents integer NOT NULL,
        last_visit_at timestamp NOT NULL,
        preferences jsonb DEFAULT '{}'::jsonb NOT NULL,
        sent_at timestamp DEFAULT NOW() NOT NULL,
        served_at timestamp,
        note text
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS vip_alerts_tenant_idx ON vip_alerts (tenant_id);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS vip_alerts_phone_idx ON vip_alerts (customer_phone);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS vip_alerts_sent_idx ON vip_alerts (sent_at);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS google_reviews (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        google_place_id text NOT NULL,
        review_id text NOT NULL UNIQUE,
        author_name text NOT NULL,
        rating integer NOT NULL,
        text text,
        time timestamp NOT NULL,
        sentiment text DEFAULT 'neutral' NOT NULL,
        response_text text,
        response_sent_at timestamp,
        created_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS google_reviews_tenant_idx ON google_reviews (tenant_id);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS google_reviews_rating_idx ON google_reviews (rating);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS google_reviews_time_idx ON google_reviews (time);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS google_places_config (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        place_id text NOT NULL,
        api_key_encrypted text,
        last_fetch_at timestamp,
        created_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS google_places_config_tenant_uniq ON google_places_config (tenant_id);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS google_places_config_tenant_idx ON google_places_config (tenant_id);
-- @@GATE-STATEMENT@@
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS review_request_sent boolean DEFAULT false NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS review_request_sent_at timestamp;
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS reservations_review_request_idx
        ON reservations (review_request_sent, date)
        WHERE status IN ('confirmed', 'completed') AND review_request_sent = false;
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS competitors (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        name text NOT NULL,
        google_place_id text NOT NULL,
        current_rating numeric DEFAULT 0 NOT NULL,
        review_count integer DEFAULT 0 NOT NULL,
        last_check_at timestamp,
        created_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS competitors_tenant_idx ON competitors (tenant_id);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS competitor_rating_history (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        competitor_id uuid NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
        rating numeric NOT NULL,
        review_count integer NOT NULL,
        recorded_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS competitor_rating_history_competitor_idx
        ON competitor_rating_history (competitor_id);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS competitors (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        name text NOT NULL,
        google_place_id text,
        current_rating numeric DEFAULT 0 NOT NULL,
        review_count integer DEFAULT 0 NOT NULL,
        last_check_at timestamp,
        created_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
ALTER TABLE competitors ADD COLUMN IF NOT EXISTS address text;
-- @@GATE-STATEMENT@@
ALTER TABLE competitors ADD COLUMN IF NOT EXISTS latitude numeric;
-- @@GATE-STATEMENT@@
ALTER TABLE competitors ADD COLUMN IF NOT EXISTS longitude numeric;
-- @@GATE-STATEMENT@@
ALTER TABLE competitors ADD COLUMN IF NOT EXISTS distance_km numeric;
-- @@GATE-STATEMENT@@
ALTER TABLE competitors ADD COLUMN IF NOT EXISTS website_url text;
-- @@GATE-STATEMENT@@
ALTER TABLE competitors ADD COLUMN IF NOT EXISTS phone text;
-- @@GATE-STATEMENT@@
ALTER TABLE competitors ADD COLUMN IF NOT EXISTS place_data jsonb DEFAULT '{}'::jsonb NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE competitors ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT NOW() NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE competitors ALTER COLUMN google_place_id DROP NOT NULL;
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS competitors_distance_idx ON competitors (distance_km);
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS address text;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS latitude numeric;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS longitude numeric;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS menu_text text;
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS competitor_menu_snapshots (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        competitor_id uuid NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
        menu_url text,
        menu_text text,
        price_range text,
        snapshot_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS competitor_menu_snapshots_competitor_idx
        ON competitor_menu_snapshots (competitor_id);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS competitor_promotions (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        competitor_id uuid NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
        promotion_text text NOT NULL,
        source text,
        detected_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS competitor_promotions_competitor_idx
        ON competitor_promotions (competitor_id);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS market_opportunities (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        key text NOT NULL,
        opportunity_type text NOT NULL,
        title text NOT NULL,
        description text NOT NULL,
        confidence numeric DEFAULT 0 NOT NULL,
        evidence jsonb DEFAULT '[]'::jsonb NOT NULL,
        addressed boolean DEFAULT false NOT NULL,
        addressed_at timestamp,
        detected_at timestamp DEFAULT NOW() NOT NULL,
        updated_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS market_opportunities_tenant_idx ON market_opportunities (tenant_id);
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS market_opportunities_tenant_key_uniq
        ON market_opportunities (tenant_id, key);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS marketing_briefs (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        brief jsonb NOT NULL,
        generated_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS marketing_briefs_tenant_idx ON marketing_briefs (tenant_id);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS marketing_briefs_tenant_generated_idx ON marketing_briefs (tenant_id, generated_at);
-- @@GATE-STATEMENT@@
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS channel text DEFAULT 'whatsapp' NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS external_id text;
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS conversations_tenant_channel_idx ON conversations (tenant_id, channel);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS conversations_tenant_external_idx ON conversations (tenant_id, external_id);
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS description text;
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS target_segment text;
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS offer text;
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS start_date timestamp;
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS end_date timestamp;
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS launched_at timestamp;
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS estimated_reach integer;
-- @@GATE-STATEMENT@@
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS estimated_revenue_cents integer;
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS campaigns_tenant_status_idx ON campaigns (tenant_id, status);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS channel_configs (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        channel text NOT NULL,
        credentials_encrypted text,
        enabled boolean DEFAULT false NOT NULL,
        created_at timestamp DEFAULT NOW() NOT NULL,
        updated_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS channel_configs_tenant_channel_idx ON channel_configs (tenant_id, channel);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS channel_configs_tenant_idx ON channel_configs (tenant_id);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS approval_requests (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
        message_text text NOT NULL,
        risk_level text NOT NULL,
        status text DEFAULT 'pending' NOT NULL,
        approved_by text,
        approved_at timestamp,
        created_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS approval_requests_tenant_status_idx ON approval_requests (tenant_id, status);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS approval_requests_conversation_idx ON approval_requests (conversation_id);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS marketing_campaigns (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        name text NOT NULL,
        description text,
        type text NOT NULL,
        target_segment text,
        offer text,
        message text NOT NULL,
        start_date timestamp,
        end_date timestamp,
        launched_at timestamp,
        estimated_reach integer,
        estimated_revenue_cents integer,
        sent_count integer DEFAULT 0 NOT NULL,
        sent_at timestamp,
        status text DEFAULT 'draft' NOT NULL,
        created_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS marketing_campaigns_tenant_idx ON marketing_campaigns (tenant_id);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS marketing_campaigns_tenant_status_idx ON marketing_campaigns (tenant_id, status);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS marketing_campaigns_tenant_type_idx ON marketing_campaigns (tenant_id, type);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS marketing_events (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        name text NOT NULL,
        description text,
        event_type text NOT NULL,
        starts_at timestamp NOT NULL,
        ends_at timestamp NOT NULL,
        location text,
        capacity integer,
        booked_count integer DEFAULT 0 NOT NULL,
        message text,
        status text DEFAULT 'draft' NOT NULL,
        created_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS marketing_events_tenant_idx ON marketing_events (tenant_id);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS marketing_events_tenant_status_idx ON marketing_events (tenant_id, status);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS marketing_events_tenant_type_idx ON marketing_events (tenant_id, event_type);
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS plan text DEFAULT 'trial' NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS plan_status text DEFAULT 'trialing' NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS trial_ends_at timestamp DEFAULT (now() + interval '14 days') NOT NULL;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS payfast_customer_token text;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS payfast_subscription_token text;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS onboarding_complete boolean DEFAULT false NOT NULL;
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS consent_records (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        consent_version text NOT NULL,
        consented_at timestamp DEFAULT NOW() NOT NULL,
        ip_address text,
        user_agent text,
        created_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS consent_records_tenant_idx ON consent_records (tenant_id);
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS owner_id text;
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS tenant_mode text DEFAULT 'live' NOT NULL;
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS brand_profiles (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        source_url text,
        logo_url text,
        logo_path text,
        primary_color text,
        secondary_color text,
        background_color text,
        font_family text,
        brand_name text,
        tagline text,
        menu_json jsonb,
        hours_json jsonb,
        google_places_id text,
        confidence real,
        extracted_at timestamp
      );
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS brand_profiles_tenant_uniq ON brand_profiles (tenant_id);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS prospects (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        name text NOT NULL,
        website text NOT NULL,
        owner_email text,
        owner_phone text,
        city text,
        status text DEFAULT 'queued' NOT NULL,
        error text,
        retries integer DEFAULT 0 NOT NULL,
        tenant_id uuid REFERENCES tenants(id) ON DELETE SET NULL,
        claim_token text,
        claimed_at timestamp,
        created_at timestamp DEFAULT NOW() NOT NULL,
        updated_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS prospects_status_idx ON prospects (status);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS prospects_tenant_idx ON prospects (tenant_id);
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS prospects_claim_token_uniq ON prospects (claim_token);
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS tenant_claim_tokens (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        token text NOT NULL,
        created_at timestamp DEFAULT NOW() NOT NULL,
        claimed_at timestamp,
        claimed_by_user_id text,
        expires_at timestamp NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS tenant_claim_tokens_token_uniq ON tenant_claim_tokens (token);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS tenant_claim_tokens_tenant_id_idx ON tenant_claim_tokens (tenant_id);
-- @@GATE-STATEMENT@@
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS owner_user_id text;
-- @@GATE-STATEMENT@@
CREATE TABLE IF NOT EXISTS memberships (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        user_id text NOT NULL,
        tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        role text DEFAULT 'owner' NOT NULL,
        created_at timestamp DEFAULT NOW() NOT NULL,
        updated_at timestamp DEFAULT NOW() NOT NULL
      );
-- @@GATE-STATEMENT@@
CREATE UNIQUE INDEX IF NOT EXISTS memberships_user_tenant_uniq ON memberships (user_id, tenant_id);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS memberships_user_idx ON memberships (user_id);
-- @@GATE-STATEMENT@@
CREATE INDEX IF NOT EXISTS memberships_tenant_idx ON memberships (tenant_id);
-- @@GATE-STATEMENT@@
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS cronjob_api_key text;
-- @@GATE-STATEMENT@@
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS demo_seed_active boolean DEFAULT false NOT NULL;`;
