'use client';
import { useEffect,useState } from 'react';

type Key={id:string;name:string;key_prefix:string;disabled:boolean;last_used_at:string|null;created_at:string};
export default function ApiKeysPage(){
 const [keys,setKeys]=useState<Key[]>([]); const [name,setName]=useState('Orderly integration'); const [secret,setSecret]=useState(''); const [error,setError]=useState('');
 async function load(){const r=await fetch('/api/api-keys',{cache:'no-store'});const d=await r.json();if(!r.ok){setError(d.error||'Could not load keys');return;}setKeys(d.keys??[])}
 useEffect(()=>{void load()},[]);
 async function create(){const r=await fetch('/api/api-keys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});const d=await r.json();if(!r.ok){setError(d.error||'Could not create key');return;}setSecret(d.key.secret);setName('Orderly integration');await load()}
 async function revoke(id:string){await fetch(`/api/api-keys/${id}`,{method:'DELETE'});await load()}
 return <div className="space-y-6"><div><h1 className="headline-md">API Keys</h1><p className="label-sm mt-1 text-app-muted">Create tenant-scoped keys for REST and MCP integrations. The secret is shown only once.</p></div><div className="glass-card p-5"><div className="flex gap-3"><input value={name} onChange={e=>setName(e.target.value)} className="flex-1 rounded-lg border p-2 bg-app-surface-0"/><button onClick={create} className="rounded-lg bg-black px-4 py-2 text-sm font-semibold text-white dark:bg-emerald-600">Create key</button></div>{secret&&<div className="mt-4 rounded-lg border border-emerald-400 bg-emerald-50 p-4"><p className="text-xs font-semibold">Copy this now — it will not be shown again.</p><code className="mt-2 block break-all text-xs">{secret}</code></div>}{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</div><div className="overflow-hidden rounded-2xl border border-app-border"><table className="w-full text-left text-sm"><thead className="bg-app-surface-1 text-xs uppercase"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Prefix</th><th className="px-4 py-3">Last used</th><th/></tr></thead><tbody className="divide-y divide-app-border">{keys.map(k=><tr key={k.id}><td className="px-4 py-3">{k.name}</td><td className="px-4 py-3 font-mono text-xs">{k.key_prefix}…</td><td className="px-4 py-3 text-app-muted">{k.last_used_at?new Date(k.last_used_at).toLocaleString('en-ZA'):'Never'}</td><td className="px-4 py-3 text-right"><button disabled={k.disabled} onClick={()=>revoke(k.id)} className="text-xs text-red-600">{k.disabled?'Revoked':'Revoke'}</button></td></tr>)}</tbody></table></div></div>
}
