'use client';
import { useEffect,useState } from 'react';
export default function WebhooksPage(){
 const [items,setItems]=useState<any[]>([]); const [url,setUrl]=useState(''); const [secret,setSecret]=useState(''); const [error,setError]=useState('');
 async function load(){const r=await fetch('/api/webhooks/endpoints',{cache:'no-store'});const d=await r.json();if(!r.ok){setError(d.error||'Could not load webhooks');return;}setItems(d.endpoints??[])} useEffect(()=>{void load()},[]);
 async function add(){const r=await fetch('/api/webhooks/endpoints',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,secret,events:['*']})});const d=await r.json();if(!r.ok){setError(d.error||'Could not add webhook');return;}setUrl('');setSecret('');await load()}
 async function del(id:string){await fetch(`/api/webhooks/endpoints/${id}`,{method:'DELETE'});await load()}
 return <div className="space-y-6"><div><h1 className="headline-md">Outbound Webhooks</h1><p className="label-sm mt-1 text-app-muted">Flavourly signs delivery requests with HMAC-SHA256 and retries failures.</p></div><div className="glass-card p-5 flex flex-col gap-3"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/flavourly/webhook" className="rounded-lg border p-2 bg-app-surface-0"/><input value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Webhook signing secret" className="rounded-lg border p-2 bg-app-surface-0"/><button onClick={add} className="self-start rounded-lg bg-black px-4 py-2 text-sm font-semibold text-white dark:bg-emerald-600">Add endpoint</button>{error&&<p className="text-sm text-red-600">{error}</p>}</div><div className="space-y-3">{items.map(x=><div key={x.id} className="glass-card p-4 flex items-center justify-between"><div><p className="text-sm font-medium">{x.url}</p><p className="text-xs text-app-muted">Events: {(x.events??['*']).join(', ')}</p></div><button onClick={()=>del(x.id)} className="text-xs text-red-600">Remove</button></div>)}</div></div>
}
